<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/models/room.glb --transform -t -k --root static
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Bed_Cloth: THREE.Mesh
      Bed_Wood: THREE.Mesh
      Cylinder001: THREE.SkinnedMesh
      Cylinder001_1: THREE.SkinnedMesh
      vintage_grandfather_clock_01_HourHand: THREE.SkinnedMesh
      vintage_grandfather_clock_01_MinuteHand: THREE.SkinnedMesh
      Cubo015: THREE.Mesh
      Cubo015_1: THREE.Mesh
      Cube: THREE.Mesh
      wooden_table_02: THREE.Mesh
      wdg_auto_free_button: THREE.Mesh
      wdg_auto_free: THREE.Mesh
      wdg_root: THREE.Mesh
      def_root: THREE.Bone
      ctrl_root: THREE.Bone
      tgt_root: THREE.Bone
    }
    materials: {
      bi_stretch: THREE.MeshStandardMaterial
      Bed_Wood: THREE.MeshStandardMaterial
      vintage_grandfather_clock_01: THREE.MeshStandardMaterial
      vintage_grandfather_clock_01_glass: THREE.MeshPhysicalMaterial
      radio: THREE.MeshStandardMaterial
      ['radio.cristal']: THREE.MeshStandardMaterial
      wooden_table_02: THREE.MeshStandardMaterial
      vintage_grandfather_clock_01: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('staticroom-transformed.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      name="Cartoon_Wood_Bed"
      position={[1.8, -0.15, -2.36]}
      rotation={[0, -1.55, 0]}
      scale={1.54}
    >
      <T.Mesh
        name="Bed_Cloth"
        geometry={gltf.nodes.Bed_Cloth.geometry}
        material={gltf.materials.bi_stretch}
      />
      <T.Mesh
        name="Bed_Wood"
        geometry={gltf.nodes.Bed_Wood.geometry}
        material={gltf.materials.Bed_Wood}
      />
    </T.Group>
    <T.Group
      name="rig_vintage_grandfather_clock_01"
      position={[-2.87, -0.06, -2.7]}
      scale={1.44}
    >
      <T is={gltf.nodes.def_root} />
      <T is={gltf.nodes.ctrl_root} />
      <T is={gltf.nodes.tgt_root} />
      <T.SkinnedMesh
        name="vintage_grandfather_clock_01_HourHand"
        geometry={gltf.nodes.vintage_grandfather_clock_01_HourHand.geometry}
        material={gltf.materials.vintage_grandfather_clock_01}
        skeleton={gltf.nodes.vintage_grandfather_clock_01_HourHand.skeleton}
      />
      <T.SkinnedMesh
        name="vintage_grandfather_clock_01_MinuteHand"
        geometry={gltf.nodes.vintage_grandfather_clock_01_MinuteHand.geometry}
        material={gltf.materials.vintage_grandfather_clock_01}
        skeleton={gltf.nodes.vintage_grandfather_clock_01_MinuteHand.skeleton}
      />
      <T.SkinnedMesh
        name="Cylinder001"
        geometry={gltf.nodes.Cylinder001.geometry}
        material={gltf.materials.vintage_grandfather_clock_01}
        skeleton={gltf.nodes.Cylinder001.skeleton}
      />
      <T.SkinnedMesh
        name="Cylinder001_1"
        geometry={gltf.nodes.Cylinder001_1.geometry}
        material={gltf.materials.vintage_grandfather_clock_01_glass}
        skeleton={gltf.nodes.Cylinder001_1.skeleton}
      />
    </T.Group>
    <T.Group
      name="Antique_radio001"
      position={[-0.86, 0.76, 0.72]}
      scale={2}
    >
      <T.Mesh
        name="Cubo015"
        geometry={gltf.nodes.Cubo015.geometry}
        material={gltf.materials.radio}
      />
      <T.Mesh
        name="Cubo015_1"
        geometry={gltf.nodes.Cubo015_1.geometry}
        material={gltf.materials['radio.cristal']}
      />
    </T.Group>
    <T.Mesh
      name="Cube"
      geometry={gltf.nodes.Cube.geometry}
      material={gltf.nodes.Cube.material}
      position={[-0.7, 1.99, 0]}
      scale={[4.13, 2.14, 3.5]}
    />
    <T.Mesh
      name="wooden_table_02"
      geometry={gltf.nodes.wooden_table_02.geometry}
      material={gltf.materials.wooden_table_02}
      position={[-0.43, -0.15, 0.66]}
      rotation={[-Math.PI, 0, -Math.PI]}
      scale={[1.69, 1.11, 1.11]}
    />
    <T.Mesh
      name="wdg_auto_free_button"
      geometry={gltf.nodes.wdg_auto_free_button.geometry}
      material={gltf.nodes.wdg_auto_free_button.material}
      position={[-2.87, -0.06, -2.7]}
      scale={1.44}
    />
    <T.Mesh
      name="wdg_auto_free"
      geometry={gltf.nodes.wdg_auto_free.geometry}
      material={gltf.nodes.wdg_auto_free.material}
      position={[-2.87, -0.06, -2.7]}
      scale={1.44}
    />
    <T.Mesh
      name="wdg_root"
      geometry={gltf.nodes.wdg_root.geometry}
      material={gltf.materials.vintage_grandfather_clock_01}
      position={[-2.87, -0.06, -2.7]}
      scale={1.44}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
